version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: luizalabs
      POSTGRES_PASSWORD: luizalabs
      POSTGRES_DB: pedido
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  db_data: