version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: luizalabs
      POSTGRES_PASSWORD: luizalabs
      POSTGRES_DB: pedido
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./script/rabbitmq-init.sh:/usr/local/bin/rabbitmq-init.sh
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    command: [ "/bin/bash", "-c", "rabbitmq-server & sleep 10 && /usr/local/bin/rabbitmq-init.sh && wait" ]

  pedido:
    build:
      context: ./pedido
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./upload_files:/app/upload_files
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pedido
      - SPRING_DATASOURCE_USERNAME=luizalabs
      - SPRING_DATASOURCE_PASSWORD=luizalabs
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - PROCESSING_DIRECTORY=/app/upload_files/processing
      - COMPLETED_DIRECTORY=/app/upload_files/completed
      - RABBITMQ_EXCHANGE=pedido-exchange
      - RABBITMQ_ROUTINGKEY=pedido-routing-key

volumes:
  db_data:
  upload_files: